import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Justin Liang</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-purple-500 to-pink-500">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Justin Liang
          </h1>
          <h2 className="text-3xl text-white sm:text-[2rem]">
            Software Developer
          </h2>
          <h2>
            <Link href="/about-me">About Me</Link>
          </h2>
          <div className="flex flex-row gap-x-4">
            <a href="https://www.linkedin.com/in/justin-liang-a25143191/"><img src="/linkedin.png" className="h-8 w-8" /></a>
            <a href="https://twitter.com/justinliang1020"><img src="twitter.png" className="h-8 w-8"/></a>
          </div>
        </div>

      </main>
    </>
  );
};

export default Home;
